In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df=pd.read_csv("/job.csv")
df

experience  score  int_score  salary
0           0    8.0          9   50000
1           0    8.0          6   45000
2           5    6.0          7   60000
3           2   10.0         10   65000
4           7    9.0          6   70000
5           3    7.0         10   62000
6          10    NaN          7   72000
7          11    7.0          8   80000

In [ ]:
median_score=df.score.median()
median_score

8.0

In [ ]:
df.score=df.score.fillna(median_score)
df

experience  score  int_score  salary
0           0    8.0          9   50000
1           0    8.0          6   45000
2           5    6.0          7   60000
3           2   10.0         10   65000
4           7    9.0          6   70000
5           3    7.0         10   62000
6          10    8.0          7   72000
7          11    7.0          8   80000

In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','score','int_score']],df.salary)

LinearRegression()

In [ ]:
reg.coef_


array([2812.95487627, 1845.70596798, 2205.24017467])

In [ ]:
reg.intercept_

17737.263464337688

In [ ]:
reg.predict([[2,9,6]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [ ]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])