In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("/content/drive/MyDrive/dataset/home.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [5]:
df.bedrooms= df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
model=linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
model.intercept_

383724.9999999998

In [14]:
model.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [11]:
#methods for save the file
#pickle metho
import pickle

In [12]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [13]:
with open('model_pickle','rb') as f:
  mp=pickle.load(f)

In [15]:
mp.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [20]:

 import joblib

In [21]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [22]:
mj=joblib.load('model_joblib')


In [23]:
mj.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])